version: "3"
services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - .:/app
    tty: true
  # cypress:
  #   depends_on:
  #     - webapp
  #   container_name: cypress
  #   environment:
  #     DEBUG: cypress:*
  #   image: cypress/included:10.0.0
  #   working_dir: /e2e
  #   volumes:
  #     - ./:/e2e
